### ISSUE TITLE
Ability to limit number of nominations per user

### ISSUE THREAD

**Issue by ThomasGaubert** [ThomasGaubert/hubot-aotw#3]
Add option to limit the number of nominations from a user. Potentially requires rewriting the brain schema.

**Comment by stevendiaz** [comment]
Thinking of tackling this.Is there a problem with doing the obvious and keeping a data structure that tracks number of nominations?

**Comment by ThomasGaubert** [comment]
Nope, there shouldn't be! If you wanted to just limit to one per user you could store nominations in a map with the username as the key, but that's too limiting IMO.

**Comment by ThomasGaubert** [comment]
Thanks @stevendiaz.

**Comment by ThomasGaubert** [comment]
Upon testing, it appears this isn't complete. Rolled back for now.
